[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.0"
hex = "0.4.3"
hex-literal = "0.3.4"
itertools = "0.10.5"
lazy_static = "1.4.0"
num = "0.4.0"
openssl = "0.10.45"
rand = "0.8.5"
snafu = "0.7.4"
